db.books.insert([
  {
    title: 'Secondhand: Travels in the New Global Garage Sale',
    description: 'Downsizing. Decluttering. A parents death. Sooner or later, all of us are faced with things we no longer need or want. But when we drop our old clothes and other items off at a local donation center, where do they go?',
    author: 'Adam Minter',
    rating: '4.10',
    published: '2019',
  },
  {
    title: 'Good Economics for Hard Times',
    description: 'The winners of the Nobel Prize show how economics, when done right, can help us solve the thorniest social and political problems of our day.Figuring out how to deal with todays critical economic problems is perhaps the great challenge of our time.',
    author: 'Abhijit V. Banerjee',
    rating: '4.22',
    published: '2019',
  },
  {
    title: 'The Unicorn Project',
    description: 'This highly anticipated follow-up to the bestselling title The Phoenix Project takes another look at Parts Unlimited, this time from the perspective of software development. In The Phoenix Project, Bill, an IT manager at Parts Unlimited, is tasked with a project critical to the future',
    author: 'Gene Kim',
    rating: '4.39',
    published: '2019',
  },
  {
    title: 'Embrace Your Weird: Face Your Fears and Unleash Creativity',
    description: 'An instant New York Times bestseller In Embrace Your Weird, New York Times bestselling author, producer, actress, TV writer, and award-winning web series creator, Felicia Day takes you on a journey to find, rekindle, or expand your creative passions. Including Felicia’s personal stories and hard-won',
    author: 'Felicia Day',
    rating: '4.16',
    published: '2019',
  },
  {
    title: 'The Infinite Game',
    description: 'Do you know how to play the game you are in? In finite games, like football or chess, the players are known, the rules are fixed, and the endpoint is clear. The winners and losers are easily identified. In infinite games, like business or politics or life itself, the players come and go, the rules',
    author: 'Simon Sinek',
    rating: '4.30',
    published: '2019',
  },
  {
    title: 'The Queens of Animation',
    description: 'In The Queens of Animation, bestselling author Nathalia Holt recounts the dramatic stories of an incredibly influential group of women who have slipped under the radar for decades but have touched all our lives. These women infiltrated the all-male domain of Disney Studios and used early',
    author: 'Nathalia Holt',
    rating: '4.12',
    published: '2019',
  },
  {
    title: 'Edison',
    description: 'From Pulitzer Prize-winning author Edmund Morris comes a revelatory new biography of Thomas Alva Edison, the most prolific genius in American history. Although Thomas Alva Edison was the most famous American of his time, and remains an international name today, he is mostly remembered only for the',
    author: 'Edmund Morris',
    rating: '3.61',
    published: '2019',
  },
  {
    title: 'Mindf*ck: Cambridge Analytica and the Plot to Break America',
    description: 'For the first time, the Cambridge Analytica whistleblower tells the inside story of the data mining and psychological manipulation behind the election of Donald Trump and the Brexit referendum, connecting Facebook, WikiLeaks, Russian intelligence, and international hackers. Mindf*ck goes deep inside',
    author: 'Christopher Wylie',
    rating: '4.51',
    published: '2019',
  },
]);
